require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec
  - rubocop-slim

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/MethodLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5
  Exclude:
    - spec/system/**/*_spec.rb

RSpec/ExampleLength:
  Exclude:
    - spec/system/**/*_spec.rb
